# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_book_name', models.CharField(max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=50)),
                ('m_author', models.CharField(max_length=30)),
                ('m_price', models.FloatField(default=0.0)),
                ('date_added_to_cart', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
