# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='client_name',
        ),
        migrations.AddField(
            model_name='cartbook',
            name='m_user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
