# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartbook_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbook',
            name='is_purchased',
            field=models.BooleanField(default=None),
        ),
    ]
