# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20160215_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='have_purchased',
        ),
    ]
