# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartbook_have_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbook',
            name='payment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.Payment'),
        ),
    ]
