# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20160215_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='payment',
        ),
        migrations.AddField(
            model_name='cartbook',
            name='purchase_bool',
            field=models.BinaryField(default=0),
        ),
    ]
