# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20160215_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbook',
            name='purchase_bool',
            field=models.IntegerField(default=0),
        ),
    ]
