# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20160215_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbook',
            old_name='purchase_bool',
            new_name='purchased_bool',
        ),
        migrations.AddField(
            model_name='cartbook',
            name='added_to_cart_bool',
            field=models.BooleanField(default=None),
        ),
    ]
