# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20160215_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='added_to_cart_bool',
        ),
    ]
