# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20160216_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbook',
            name='added_to_cart_bool',
            field=models.IntegerField(default=0),
        ),
    ]
