# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20160216_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbook',
            name='date_added_to_cart',
        ),
    ]
