# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20160216_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbook',
            name='date_purchased',
            field=models.DateTimeField(blank=True),
        ),
    ]
