# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_auto_20160217_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='totaled_date',
            field=models.DateTimeField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
