# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20160212_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
