# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_book_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='upload',
            new_name='upload_image',
        ),
    ]
