# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20160213_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_to_cart_bool',
            field=models.BooleanField(default=None),
        ),
    ]
