# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_book_added_to_cart_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_to_cart_bool',
            field=models.IntegerField(default=0),
        ),
    ]
