# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20160215_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_to_cart_bool',
            field=models.BooleanField(default=None),
        ),
    ]
