# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20160215_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_to_cart_bool',
        ),
    ]
